#!/usr/bin/env bash

set -eux

mkdir -p temp/{cache,sessions} log builder/temp

npm install
composer install --no-suggest --no-progress --no-dev --ignore-platform-reqs
node_modules/.bin/gulp

chmod -R go-rwx .
chmod g+rx . .ci .ci/release .ci/release-bundle
chmod -R g+r public
find public -type d -exec chmod g+x '{}' \;
