#!/usr/bin/env bash

set -eux

RELEASES_DIR="$DEPLOY_PATH/releases"
TARGET_DIR_VERSIONED="$RELEASES_DIR/$BUILD_ID"
TARGET_DIR_AUTHORITATIVE="$DEPLOY_PATH/current"
SHARED_DIR="$DEPLOY_PATH/shared"

rsync -rzpEl -e "ssh -i '$DEPLOY_KEY_PATH'" --exclude=.git --exclude=.ci/keys ./ "$DEPLOY_USER@$DEPLOY_SERVER:$TARGET_DIR_VERSIONED"

ssh -T -i "$DEPLOY_KEY_PATH" "$DEPLOY_USER@$DEPLOY_SERVER" << EOT
set -eux

rm -rf "$TARGET_DIR_VERSIONED/log"
rm -rf "$TARGET_DIR_VERSIONED/temp/sessions"
rm -rf "$TARGET_DIR_VERSIONED/public/releases"
rm -rf "$TARGET_DIR_VERSIONED/builder/temp"
rm -rf "$TARGET_DIR_VERSIONED/builder/node_modules"
rm -rf "$TARGET_DIR_VERSIONED/builder/package-lock.json"
rm -f "$TARGET_DIR_VERSIONED/app/config/config.local.neon"

ln -sfnT "$SHARED_DIR/log" "$TARGET_DIR_VERSIONED/log"
ln -sfnT "$SHARED_DIR/temp/sessions" "$TARGET_DIR_VERSIONED/temp/sessions"
ln -sfnT "$SHARED_DIR/public/releases" "$TARGET_DIR_VERSIONED/public/releases"
ln -sfnT "$SHARED_DIR/builder/temp" "$TARGET_DIR_VERSIONED/builder/temp"
ln -sfnT "$SHARED_DIR/builder/node_modules" "$TARGET_DIR_VERSIONED/builder/node_modules"
ln -sfnT "$SHARED_DIR/builder/package-lock.json" "$TARGET_DIR_VERSIONED/builder/package-lock.json"
ln -sfnT "$SHARED_DIR/app/config/config.local.neon" "$TARGET_DIR_VERSIONED/app/config/config.local.neon"

ln -sfnT "$TARGET_DIR_VERSIONED" "$TARGET_DIR_AUTHORITATIVE.new"
mv -fT "$TARGET_DIR_AUTHORITATIVE.new" "$TARGET_DIR_AUTHORITATIVE"

cachetool opcache:reset --fcgi=/run/php/nittro.org.sock

ls -1v "$RELEASES_DIR" | grep -E '^[0-9]+$' | head -n -5 | sed -e "s#^#$RELEASES_DIR/#" | xargs -r rm -rf
EOT
