#!/usr/bin/env bash

set -eux

PACKAGE_NAME="$( php -r 'echo json_decode(file_get_contents("package.json"))->name;' )"
PACKAGE_VERSION="$( php -r 'echo json_decode(file_get_contents("package.json"))->version;' )"
ARCHIVE_FILENAME="$PACKAGE_NAME-$PACKAGE_VERSION.zip"
RELEASES_DIR="$DEPLOY_PATH/shared/public/releases"

npm ci
node_modules/.bin/gulp release

rsync -rzpEl -e "ssh -i '$DEPLOY_KEY_PATH'" "dist/$ARCHIVE_FILENAME" "$DEPLOY_USER@$DEPLOY_SERVER:$RELEASES_DIR/$ARCHIVE_FILENAME"

ssh -T -i "$DEPLOY_KEY_PATH" "$DEPLOY_USER@$DEPLOY_SERVER" << EOT
set -eux

cd "$DEPLOY_PATH/current"

php app/update-bundle-version.php "$PACKAGE_NAME" "$PACKAGE_VERSION"
rm -rf temp/cache/*
cachetool opcache:reset --fcgi=/run/php/nittro.org.sock

EOT
